### ISSUE TITLE
Instarepl keeps stacking evaluation results for defns

### ISSUE THREAD

**Issue by berendbaas** [LightTable/Clojure#32]
My apologies if I'm describing this somewhat unclearly, but I'll try to assist this with screenshots to make it clearer.

Whenever using the instarepl and defining a function, every edit in the instarepl causes the function to be reevaluated and the inline-eval results to be displayed after the previous evaluation. This eventually crashes LightTable for me. The problem seems to have started after updating the Clojure plugin to 0.0.14
Specs:
Macbook Pro 2012, Mac OS X 10.10 Yosemite
Light Table 0.6.7, Binary version 0.8.4

Steps to reproduce
1. Start LightTable and open up an instarepl.
2. define the following example function 
```clojure
(defn x [a b] (+ a b))
```
3. call the function once (x 2 3)
4. Edit the instarepl above or below the defined function (in the screenshot i added (+ 2 2)
5. repeat step 4 a couple of times to see the evaluations stack up.
![screen shot 2014-11-09 at 16 06 59](https://cloud.githubusercontent.com/assets/3963067/4967750/d87d3dc4-6822-11e4-9947-0b0577762e53.png)

**Comment by joshuafcole** [comment]
The problem is resolved in 0.1.1 of the Clojure plugin. Cheers!

**Comment by alhimik45** [comment]
Still have this problem with `doseq`. Just type simple doseq form and start typing after it. Every evaluation there are will be new inlines:

![](http://hsto.org/files/6ae/21c/b55/6ae21cb55f0447f489318b52636b0380.png)
